name: build

on:
  push:
    branches: [ "main" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm install -g @marp-team/marp-cli 
      - run: |
          mkdir dist
          marp slide.md --html --output dist/index.html --title "AUTD3 講習会"
          cp *.svg dist/
          cp *.jpg dist/
          cp *.js dist/
      - uses: actions/configure-pages@v2
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true